name: Python Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t python-app:latest .

    - name: Run Tests in Docker

      run: |
         docker run --rm -p 8000:8000 python-app:latest --endpoints="https://www.google.com" --ci